### ISSUE TITLE
Unable to run on XCode 11

### ISSUE THREAD

**Issue by keshavgn** [qiscus/QiscusCore-iOS#2]
Hi, 
We(Halodoc) are using QiscusCore 0.3.4, with Swift 5. it works fine on XCode 10, but getting compile error on XCode 11. 

here is the error details:
Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: /Users/keshavgn/Desktop/Projects/halodoc-ios/Pods/QiscusCore/QiscusCore.framework/Modules/QiscusCore.swiftmodule/i386.swiftmodule

could you let us know what is the issue?

**Comment by ariefnurputranto** [comment]
please using QiscusCore 0.3.5, it's still happend or not.

**Comment by keshavgn** [comment]
Yes the issue is same on v0.3.5 as well, I just checked it some time back.

**Comment by ariefnurputranto** [comment]
ok. Will check sir.

**Comment by ariefnurputranto** [comment]
I think this is still a beta version for Xcode 11, we will put it in our roadmap. thanks for your feedback sir @keshavgn

**Comment by keshavgn** [comment]
Sure, Thank you

**Comment by ariefnurputranto** [comment]
was released in beta version, you can try this version https://github.com/qiscus/QiscusCore-iOS/releases/tag/0.4.0-beta2
