### ISSUE TITLE
[QiscusCore] Error: failed to send Online status

### ISSUE THREAD

**Issue by SaadFurqanDis** [qiscus/QiscusCore-iOS#4]
every time i run the app, i got this error message.
it seems like sdk trying to send loggedin user Online status but fail for some reason.
plz have a look.

**Comment by ariefnurputranto** [comment]
do you call QiscusCore.setup() and QiscusCore.connect()?

for QiscusCore.setup, you can follow this sample
https://github.com/qiscus/qiscus-chat-sdk-ios-sample/blob/25529bb92ba95df260a901c54d83f3272d95337a/Example/AppDelegate.swift#L25

and for QiscusCore.connect, you can follow this sample
https://github.com/qiscus/qiscus-chat-sdk-ios-sample/blob/25529bb92ba95df260a901c54d83f3272d95337a/Example/AppDelegate.swift#L125
