### ISSUE TITLE
Cannot upload more than 10 MB

### ISSUE THREAD

**Issue by valabal** [qiscus/QiscusCore-iOS#6]
Hi! I'm trying to use QiscusCore upload function in my project, if I tried to upload files (video) more than 10 MB, the qiscuss server will always return " Error: json: {
    error =     {message = "Request error: 400 Bad Request";};
    status = 500;}"

Its works fine if we tried to upload video less than 10MB (example 5MB-8MB)
can you help us?

**Comment by valabal** [comment]
[10MBMp4.mp4.zip](https://github.com/qiscus/QiscusCore-iOS/files/4053019/10MBMp4.mp4.zip)
This is the sample file that I used..

**Comment by ariefnurputranto** [comment]
I can upload with your video sample sir.

can you check your internet sir? and try again when the internet is fast.

**Comment by valabal** [comment]
thats weird.. I'm still failed (goes to the error callback) even though my connection was fine...
I'm using simulator by the way.. does it related? (our tester report to me that they can upload the videos just fine using the real device)
FYI : I'm tracking the progress via the onProgress callback.. the files was uploaded successfully.. (its progress was at 100%).. but instead calling the success callback.. its called the error callback... so we can't get the uploaded path)

**Comment by ariefnurputranto** [comment]
i try using simulator iphone 6 or 11 can success upload.

can you try other version simulator sir?? or using the real device

**Comment by valabal** [comment]
Thanks..I think I know the issue is.. 
after I lowercased the filenames, suddenly the videos are enable to upload...
