### ISSUE TITLE
Support Xcode 11.4.1

### ISSUE THREAD

**Issue by dimohamdy** [qiscus/QiscusCore-iOS#7]
Please update the SDK to support Xcode 11.4.1 to with Swift 5.2.2

**Comment by dimohamdy** [comment]
Please use ABI swift 5.1 feature 
check this link to enable it https://stackoverflow.com/a/59985752/3806350

**Comment by dimohamdy** [comment]
@ariefnurputranto 
Any update about support

**Comment by ariefnurputranto** [comment]
Soon, i will support XCode 11.4.1 in this week.

**Comment by dimohamdy** [comment]
@ariefnurputranto did you use ABI feature in Swift5
