### ISSUE TITLE
Can't install in an app extension

### ISSUE THREAD

**Issue by i-gotchu-dude** [qiscus/QiscusCore-iOS#9]
I've tried add QiscusCore sdk as depencies into my app extension and get this error

`'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.`
QiscusWorkerManager line 19, and RealtimeManager line 669

**Comment by ariefnurputranto** [comment]
hi @i-gotchu-dude,

Does this help https://stackoverflow.com/questions/34225213/uiapplication-sharedapplication-not-available?

or using this :

- Set to Allow API Extension to No to particular framework who gives this e
error
- Consider you facing this issue and you installed this framework using Pod. Then your project click on Pod -> CLick on QiscusCore.
- And set Allow API Extension to No

**Comment by i-gotchu-dude** [comment]
As I read the solution from your given link one of the user explained that 
`The Apple store will probably reject your app if you have an app extension and set the requirement to No`

So I dive deep to read the apple developer documentation, and they indeed say the same thing
`Make sure your embedded framework does not contain APIs unavailable to app extensions, as described in Some APIs Are Unavailable to App Extensions. If you have a custom framework that does contain such APIs, you can safely link to it from your containing app but cannot share that code with the app’s contained extensions. The App Store rejects any app extension that links to such frameworks or that otherwise uses unavailable APIs. `

source: https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html

**Comment by ariefnurputranto** [comment]
hi @i-gotchu-dude , can you explain the flow and how to use the case? why use an app extension?

**Comment by i-gotchu-dude** [comment]
For instance, I would like to add Share Extension into my app, which's a common feature for a chat app, the user will be able to share photos or files directly from the Photos/Files app, but that requires some functionality in QiscusCore that need to be imported in Share Extension.
Another use case is in the new feature in iOS called Widget, I want my app to have some snippet chat.

**Comment by ariefnurputranto** [comment]
hi @i-gotchu-dude , when you change in the error code with :

```
 let stateApp = UIApplication.value(forKeyPath: #keyPath(UIApplication.shared)) as! UIApplication
 let state = stateApp.applicationState
```

does it work sir? if work, i will release beta version for you

**Comment by i-gotchu-dude** [comment]
hi @ariefnurputranto sorry for the late response
Yes it does work when I changed the code with your suggestion, the error is gone now
but probably it needs some testing to see whether is affecting another feature/code or not, please let me know 

Thanks

**Comment by ariefnurputranto** [comment]
This week I will double check, it looks like it has no effect on the other code

If it doesn't affect the other code, I'll build the beta version on Monday.
I'll let you know when it's released

**Comment by ariefnurputranto** [comment]
hi @i-gotchu-dude , sorry for making you wait so long 

you can use this version https://github.com/qiscus/QiscusCore-iOS/releases/tag/1.5.11-beta.2
